name: Build (CI)

on:
  push:
    branches-ignore:
      - root

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          java-version: 21
          distribution: temurin

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle (Build)
        run: "./gradlew build"

      - name: Upload artifacts (Distribution)
        uses: actions/upload-artifact@v5

        with:
          name: JARs
          path: build/distributions/*.tar
